export const TOGGLE_LOGIN_MODAL = 'TOGGLE_LOGIN_MODAL';
export const TOGGLE_SIGN_UP_MODAL = 'TOGGLE_SIGN_UP_MODAL';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESSFUL = 'SIGN_UP_SUCCESSFUL';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESSFUL = 'LOGOUT_SUCCESSFUL';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const GET_USR_INFO = 'GET_USR_INFO';
export const GET_USR_INFO_SUCCESSFUL = 'GET_USR_INFO_SUCCESSFUL';
export const GET_USR_INFO_FAILURE = 'GET_USR_INFO_FAILURE';
