export const SOCKET = {
  CONNECTION: "CONNECTION",
  DISCONNECTION: "DISCONNECTION",
  JOIN_ROOM: "JOIN_ROOM",
  LEAVE_ROOM: "LEAVE_ROOM",
  COMMENT: "COMMENT",
  NEW_COMMENT: "NEW_COMMENT",
  REPLY_COMMENT: "REPLY_COMMENT",
  NEW_REPLY_COMMENT: "NEW_REPLY_COMMENT",
};
